### ISSUE TITLE
(500 Internal Server Error)

### ISSUE THREAD

**Issue by Levetofte** [qburst/qbmeetingroomplugin#5]
Hi,

I am new to Redmine, Rails and ruby..

I have installed the plugin and get a 500 internal Server error.
I have made all exept for the "edit" of the init.rb file. Please explain that..
I get the "Book meeting" link in the top menu, but not in the project menu - but as only link when under project.

Please see log:

Processing ApplicationController#index (for 10.126.33.109 at 2012-09-13 12:56:23) [GET]
  Parameters: {"controller"=>"meeting_calendars", "action"=>"index"}

NoMethodError (undefined method `possible_values' for nil:NilClass):
  vendor/plugins/redmine_meeting_room_calendar/vendor/plugins/redmine_meeting_room_calendar/app/controllers/meeting_calendars_controller.rb:11:in`initialize'
  passenger (3.0.12) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:513:in`accept_and_process_next_request'
  passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  passenger (3.0.12) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in`start_request_handler'
  passenger (3.0.12) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
  passenger (3.0.12) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in`handle_spawn_application'
  passenger (3.0.12) lib/phusion_passenger/utils.rb:479:in `safe_fork'
  passenger (3.0.12) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in`handle_spawn_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:180:in`start'
  passenger (3.0.12) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:219:in`spawn_rails_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:214:in`spawn_rails_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
  passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:79:in`synchronize'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:132:in`spawn_application'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in`**send**'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  passenger (3.0.12) helper-scripts/passenger-spawn-server:99

Rendering /opt/bitnami/apps/redmine/htdocs/public/500.html (500 Internal Server Error)

**Comment by istupin** [comment]
It seems you have wrong values in meeting_calendars_controller.rb. I'm not a developer, but i suggest you try changing that:
@meeting_rooms=@custom_field[4].possible_values
